import {
  PPT_TEXT_CHAR_WIDTH_FACTOR,
  PPT_TEXT_FULL_WIDTH_EM,
  PPT_TEXT_LINE_HEIGHT_FACTOR,
  PPT_TEXT_PIXELS_PER_INCH,
  PPT_TEXT_SAFE_WIDTH_RATIO,
  PPT_TEXT_SAFE_HEIGHT_PADDING,
  calculateSafeTextBoxHeight,
  recommendSingleLineChars,
} from './ppt-text-layout.ts';

const COVER_TITLE_HEIGHT = calculateSafeTextBoxHeight(88);
const PAGE_TITLE_HEIGHT = calculateSafeTextBoxHeight(72);
const SECTION_TITLE_HEIGHT = calculateSafeTextBoxHeight(56);
const BODY_TEXT_HEIGHT = calculateSafeTextBoxHeight(48);
const THREE_LINE_BODY_HEIGHT = calculateSafeTextBoxHeight(48, 3);
const AGENDA_DESC_SAFE_CHARS = recommendSingleLineChars(6.98, 48);
const BODY_SIDE_TEXT_SAFE_CHARS = recommendSingleLineChars(5.16, 48);

export const PPTXGENJS_GUIDE = [
  'PptxGenJS 使用指南（给内置 PPT 助手）：',
  '',
  '一、先牢记当前项目运行环境',
  '1. index.js 必须导出函数：module.exports = async function buildPresentation({ pptx, pptxgenjs, getResourceUrl, getResourcePath, measureText, log, projectId, projectDir, path }) { ... }。',
  '2. 可用上下文：',
  '   - context.pptx：当前演示文稿实例，常用枚举也挂在这个实例上，例如 pptx.ShapeType.roundRect、pptx.ChartType.bar、pptx.AlignH.center。',
  '   - context.pptxgenjs：PptxGenJS 构造函数本身，可用于判断实例类型，例如 pptx instanceof pptxgenjs。',
  '   - context.getResourceUrl(fileName)：把项目中的图片/媒体文件转成浏览器可访问地址。',
  '   - context.getResourcePath(fileName)：把项目中的文件转成本地路径（仅后端运行可用）。',
  '   - context.measureText(text, { fontSize, fontFace, width? })：前端预览会用 canvas + 真实字体名测量文字尺寸，返回 width、widthInches、height、safeHeight、lineHeight、lines。',
  '   - context.log(...args)：输出运行日志，方便排错。',
  '   - context.projectId / context.projectDir / context.path：当前项目信息。',
  '3. 框架会负责预览、导出和写文件，不要在 index.js 里自己调用 writeFile / write / saveAs。',
  '4. 不要 import / require 外部模块；只能使用框架提供的上下文和标准 JavaScript 语法。',
  '5. 完成内容后要保证脚本能直接运行，优先输出完整可交付的 PPT，而不是只有一页占位页。',
  '',
  '二、推荐起手模板',
  "module.exports = async function buildPresentation({ pptx, measureText, getResourceUrl, log }) {",
  "  pptx.layout = 'LAYOUT_WIDE';",
  "  pptx.author = 'last-version-ppt';",
  "  pptx.subject = '自动生成演示文稿';",
  "  pptx.title = '项目标题';",
  "  pptx.company = 'last-version-ppt';",
  "  pptx.lang = 'zh-CN';",
  '',
  "  const fontFace = 'Noto Sans CJK SC';",
  '  const page = { left: 0.72, top: 0.52, width: 11.56 };',
  '  const textOptions = { fontFace, margin: 0 };',
  '  const slide = pptx.addSlide();',
  "  slide.background = { color: 'F8FAFC' };",
  "  const titleMetrics = await measureText('主标题', { fontSize: 88, fontFace, width: page.width });",
  `  slide.addText('主标题', { ...textOptions, x: page.left, y: 0.76, w: page.width, h: titleMetrics.safeHeight, fontSize: 88, bold: true, color: '0F172A' });`,
  "  const subtitleY = 0.76 + titleMetrics.safeHeight + 0.44;",
  "  const subtitleMetrics = await measureText('副标题或说明', { fontSize: 56, fontFace, width: page.width });",
  "  slide.addText('副标题或说明', { ...textOptions, x: page.left, y: subtitleY, w: page.width, h: subtitleMetrics.safeHeight, fontSize: 56, color: '475569' });",
  "  log('封面已生成');",
  '};',
  '',
  '三、Presentation 级 API（演示文稿级）',
  "1. 页面比例：优先使用 pptx.layout = 'LAYOUT_WIDE'；它对应 13.333 × 7.5 英寸的 16:9 页面。内置比例还包括 'LAYOUT_16x9' 和 'LAYOUT_4x3'。",
  '2. 自定义比例：pptx.defineLayout({ name: "CUSTOM", width: 13.333, height: 7.5 }); 然后 pptx.layout = "CUSTOM"。如果只是常规宽屏，不要重复自定义。',
  '3. 元信息：pptx.author / company / subject / title / lang / theme / rtlMode / layout。',
  '4. 幻灯片：pptx.addSlide() 新增页面；pptx._slides.length 可用于了解当前页数（尽量只读不改内部结构）。',
  '5. 母版与主题：可使用 pptx.defineTheme(...)、pptx.theme = {...}、pptx.defineSlideMaster(...) 统一标题、页脚、背景。',
  '6. 导出相关 API 如 pptx.writeFile()/write() 由框架托管，本项目中不要主动调用。',
  '',
  '四、Slide 级 API（每一页常用能力）',
  '1. 新增页面：const slide = pptx.addSlide();',
  "2. 背景色：slide.background = { color: 'F8FAFC' };",
  '3. 备注：slide.addNotes("讲解备注");',
  '4. 页面编号、页眉页脚、版式可以通过母版或统一函数封装。',
  '5. 常见排版思路：封面 / 目录 / 问题 / 方案 / 亮点 / 数据 / 计划 / 收尾，保证信息完整。',
  '',
  '五、文本 API（最常用）',
  '1. 纯文本：slide.addText("标题", { x, y, w, h, fontSize, bold, color, align, valign });',
  '2. 富文本：slide.addText([{ text: "营收", options: { bold: true } }, { text: " +32%" }], { x, y, w, h });',
  '3. 常用选项：',
   '   - 位置尺寸：x, y, w, h',
   '   - 字体：fontFace, fontSize, bold, italic, color, margin',
   '   - 对齐：align, valign；富文本分段换行时可用 breakLine',
   '   - 背景与边框：fill: { color }, line: { color, pt }',
   '   - 项目符号：bullet: { indent }',
   '   - 段落：paraSpaceAfterPt, paraSpaceBeforePt',
   '   - 参考常见 16:9 商务模板：封面大标题常见 44~60、副标题 28~32、页标题 32~40、正文 20~24、备注 16~18。',
   '   - 本项目默认建议：封面主标题 88、页标题 72、副标题 56、正文 48；需要更密的内容时，优先加大文本框高度和宽度，再考虑把正文降到 40。',
   `   - 文本框理论高度公式：h = fontSize × ${PPT_TEXT_LINE_HEIGHT_FACTOR} ÷ 100 × 行数（单位：英寸，和 PptxGenJS 内部的 LINEH_MODIFIER 一致）。`,
   `   - 示例安全高度公式：safeH = h + ${PPT_TEXT_SAFE_HEIGHT_PADDING.toFixed(2)}，再向上取两位小数；也就是 88→${COVER_TITLE_HEIGHT}、72→${PAGE_TITLE_HEIGHT}、56→${SECTION_TITLE_HEIGHT}、48→${BODY_TEXT_HEIGHT}，48 号字三行正文至少 ${THREE_LINE_BODY_HEIGHT}。`,
    `   - 需要真实测量时，优先调用 context.measureText(text, { fontSize, fontFace: 'Noto Sans CJK SC', width })；前端预览会用 canvas 和真实字体名测量，再按 widthPx <= w × 96 × ${PPT_TEXT_SAFE_WIDTH_RATIO.toFixed(2)} 做换行判断。`,
    `   - 估算时可先按中文和全角标点约 ${PPT_TEXT_FULL_WIDTH_EM.toFixed(2)}em 来算；在 96dpi 预览里相当于约 ${(PPT_TEXT_PIXELS_PER_INCH / 72).toFixed(2)} × fontSize（fontSize 传入的是 pt，需要先换算成 px），所以单行容字公式可写成 maxChars = floor(floor(w × 72) × ${PPT_TEXT_CHAR_WIDTH_FACTOR} ÷ fontSize)。这个公式已经按 ${PPT_TEXT_SAFE_WIDTH_RATIO.toFixed(2)} 的安全宽度折算；当前 recommendSingleLineChars 和 maxChars 一致，因为固定预留字符现在就是 0。`,
     `   - 目录说明框 w 6.98、fontSize 48 时，按安全宽度折算约 ${AGENDA_DESC_SAFE_CHARS} 字；示例文案请不要超过这个数量。`,
     `   - 正文右侧说明框 w 5.16、fontSize 48 时，按安全宽度折算约 ${BODY_SIDE_TEXT_SAFE_CHARS} 字；示例文案建议控制在这个数量以内，避免被 PowerPoint 自动换行。`,
   '   - 尺寸建议：默认留出左右各 0.72 英寸边距，大标题和正文文本框建议显式设置 margin: 0；不要依赖默认内边距。',
   '4. 标题示例：',
   `   slide.addText('年度经营复盘', { margin: 0, x: 0.72, y: 0.52, w: 11.56, h: ${PAGE_TITLE_HEIGHT}, fontSize: 72, bold: true, color: '0F172A' });`,
   '5. 简单换行（最稳妥）：',
   `   slide.addText('• 收入同比提升 32%\\n• 新客转化率提升 11%\\n• 重点区域已完成覆盖', { margin: 0, x: 0.96, y: 2.74, w: 4.36, h: ${THREE_LINE_BODY_HEIGHT}, fontSize: 48, color: '334155' });`,
   '6. 富文本分段换行（只有在需要单独控制每段样式时再用）：',
  '   slide.addText([',
  "     { text: '• 收入同比提升 32%', options: { color: '0F766E', breakLine: true } },",
  "     { text: '• 新客转化率提升 11%', options: { color: '1D4ED8', breakLine: true } },",
  "     { text: '• 重点区域已完成覆盖', options: { color: '334155' } }",
   `   ], { margin: 0, x: 6.4, y: 4.64, w: 5.16, h: ${BODY_TEXT_HEIGHT}, fontSize: 48 });`,
  '',
  '六、图片与媒体 API',
  '1. 本地资源优先使用 getResourceUrl("文件名.png")；如果只在后端导出时需要绝对路径，可用 getResourcePath("文件名.png")。',
  '2. 基础写法：slide.addImage({ path: getResourceUrl("cover.png"), x, y, w, h });',
  '3. 常用选项：x, y, w, h, path, data, transparency, rounding。',
  '4. 按比例裁切：slide.addImage({ path, x, y, w, h, sizing: { type: "cover", x, y, w, h } });',
  '5. 完整放入：slide.addImage({ path, x, y, w, h, sizing: { type: "contain", x, y, w, h } });',
  '6. 实战建议：图片不要拉伸变形；人物图适合 cover，海报/截图适合 contain。',
  '',
  '七、形状与线条 API',
  '1. 矩形：slide.addShape(pptx.ShapeType.rect, { x, y, w, h, fill: { color }, line: { color } });',
  '2. 圆角矩形：slide.addShape(pptx.ShapeType.roundRect, { ... });',
  '3. 线条：slide.addText("流程", ...); slide.addShape(pptx.ShapeType.line, { x, y, w, h, line: { color, pt, beginArrowType, endArrowType } });',
  '4. 常见形状：rect、roundRect、ellipse、line、chevron、rightArrow、hexagon。',
  '5. 卡片示例：',
  "   slide.addShape(pptx.ShapeType.roundRect, { x: 0.8, y: 1.6, w: 3.7, h: 1.8, rectRadius: 0.08, fill: { color: 'FFFFFF' }, line: { color: 'E2E8F0', pt: 1 } });",
  '',
  '八、表格 API',
  '1. 基础写法：slide.addTable(rows, { x, y, w, h });',
  '2. rows 是二维数组，例如：',
  "   const rows = [['项目', '数值', '说明'], ['营收', '520 万', '同比增长 32%'], ['毛利率', '48%', '持续改善']];",
  '3. 常用选项：border, fill, color, fontSize, margin, rowH, colW, align, valign。',
  '4. 表头建议加深底色并加粗，数据列右对齐，说明列左对齐。',
  '',
  '九、图表 API',
  '1. 基础写法：slide.addChart(chartType, series, { x, y, w, h, catAxisLabelFontSize, valAxisLabelFontSize, showLegend });',
  '2. 柱状图：pptx.ChartType.bar。',
  '3. 折线图：pptx.ChartType.line。',
  '4. 饼图：pptx.ChartType.pie / pptx.ChartType.doughnut。',
  '5. series 示例：',
  '   const series = [',
  "     { name: '营收', labels: ['一月', '二月', '三月'], values: [120, 180, 240] },",
  "     { name: '利润', labels: ['一月', '二月', '三月'], values: [30, 56, 88] }",
  '   ];',
  '6. 图表建议：页内不要堆太多图；每页一个核心结论，搭配 1 个图和 2~4 条解释。',
  '',
  '十、常见页面模板示例',
  '1. 封面：大标题 + 副标题 + 背景图/品牌色。',
  '2. 目录：3~6 个章节，编号清晰。',
  '3. 三栏亮点页：三个卡片，每个卡片含标题、短句和图标/数字。',
  '4. 数据页：左图右文，图表解释必须写结论。',
  '5. 计划页：时间线 + 节点说明。',
  '6. 结尾页：一句总结 + 下一步动作 + 联系方式/致谢。',
  '',
  '十一、适合本项目的完整示例',
  "module.exports = async function buildPresentation({ pptx, measureText, getResourceUrl, log }) {",
  "  pptx.layout = 'LAYOUT_WIDE';",
  "  pptx.title = '新品发布方案';",
  "  pptx.subject = '封面、目录、正文三页产品发布演示';",
  "  const fontFace = 'Noto Sans CJK SC';",
  '  const page = { left: 0.72, width: 11.56, titleTop: 0.52 };',
  '  const textOptions = { fontFace, margin: 0 };',
  '',
  '  const cover = pptx.addSlide();',
  "  cover.background = { color: '0F172A' };",
  "  const coverTitle = await measureText('新品发布方案', { fontSize: 88, fontFace, width: page.width });",
  "  const coverSubtitleY = 0.76 + coverTitle.safeHeight + 0.44;",
  "  const coverSubtitle = await measureText('更快上手、更好转化、更强品牌感知', { fontSize: 56, fontFace, width: 10.8 });",
  "  cover.addText('新品发布方案', { ...textOptions, x: page.left, y: 0.76, w: page.width, h: coverTitle.safeHeight, fontSize: 88, bold: true, color: 'FFFFFF' });",
  "  cover.addText('更快上手、更好转化、更强品牌感知', { ...textOptions, x: page.left, y: coverSubtitleY, w: 10.8, h: coverSubtitle.safeHeight, fontSize: 56, color: 'CBD5E1' });",
  "  cover.addText('把一句核心价值放在封面下半区，更容易记住重点。', { ...textOptions, x: page.left, y: coverSubtitleY + coverSubtitle.safeHeight + 0.28, w: page.width, h: 0.83, fontSize: 48, color: 'E2E8F0' });",
  '',
  '  const agenda = pptx.addSlide();',
  "  agenda.background = { color: 'F8FAFC' };",
  `  agenda.addText('目录', { ...textOptions, x: page.left, y: page.titleTop, w: page.width, h: ${PAGE_TITLE_HEIGHT}, fontSize: 72, bold: true, color: '0F172A' });`,
  '  [',
    "    { no: '01', title: '背景与目标', desc: '先讲这次发布要解决什么。' },",
    "    { no: '02', title: '核心亮点', desc: '用三条亮点讲清价值。' },",
    "    { no: '03', title: '落地计划', desc: '给出时间、动作和负责人。' }",
  '  ].forEach((item, index) => {',
  '    const y = 1.42 + index * 1.62;',
    `    agenda.addText(item.no, { ...textOptions, x: page.left, y, w: 0.9, h: ${SECTION_TITLE_HEIGHT}, fontSize: 56, bold: true, color: '2563EB' });`,
    `    agenda.addText(item.title, { ...textOptions, x: 1.9, y: y + 0.04, w: 2.6, h: ${BODY_TEXT_HEIGHT}, fontSize: 48, bold: true, color: '0F172A' });`,
    `    agenda.addText(item.desc, { ...textOptions, x: 4.94, y: y + 0.04, w: 6.98, h: ${BODY_TEXT_HEIGHT}, fontSize: 48, color: '475569' });`,
  '  });',
  '',
  '  const body = pptx.addSlide();',
  "  body.background = { color: 'FFFFFF' };",
  `  body.addText('核心亮点展开', { ...textOptions, x: page.left, y: page.titleTop, w: page.width, h: ${PAGE_TITLE_HEIGHT}, fontSize: 72, bold: true, color: '0F172A' });`,
  `  body.addText('为什么值得做', { ...textOptions, x: page.left, y: 1.56, w: 3.8, h: ${SECTION_TITLE_HEIGHT}, fontSize: 56, bold: true, color: '0F172A' });`,
  `  body.addText('• 帮用户更快理解价值\\n• 帮团队统一对外表达\\n• 帮销售更顺利推进转化', { ...textOptions, x: page.left, y: 2.52, w: 5.24, h: ${THREE_LINE_BODY_HEIGHT}, fontSize: 48, color: '334155' });`,
  `  body.addText('关键数字', { ...textOptions, x: 6.32, y: 1.56, w: 2.7, h: ${SECTION_TITLE_HEIGHT}, fontSize: 56, bold: true, color: '1D4ED8' });`,
   `  body.addText('先放关键结果。', { ...textOptions, x: 6.32, y: 2.52, w: 5.2, h: ${BODY_TEXT_HEIGHT}, fontSize: 48, color: '1E3A8A' });`,
  `  body.addText('下一步动作', { ...textOptions, x: 6.32, y: 4.14, w: 3.2, h: ${SECTION_TITLE_HEIGHT}, fontSize: 56, bold: true, color: '0F172A' });`,
   `  body.addText('写清时间安排。', { ...textOptions, x: 6.32, y: 5.1, w: 5.16, h: ${BODY_TEXT_HEIGHT}, fontSize: 48, color: '475569' });`,
  '',
  "  log('已生成封面、目录、正文 3 页新品发布方案');",
  '};',
  '',
  '十二、生成时的质量要求',
  '1. 每一页都要有明确标题，重要信息不要只靠一段长文字。',
  '2. 页数、结构、内容必须符合用户要求；如果用户要完整方案，不要只给简单骨架。',
  '3. 优先使用中文文案，避免英文占位词。',
  '4. 图片、表格、图表需要与页面结论一致，不能只堆元素。',
  '5. 输出前自检：是否有封面、核心内容页、收尾页；是否排版整齐；是否容易读懂。',
].join('\n');
