export const PPTXGENJS_GUIDE = [
  'PptxGenJS 使用指南（给内置 PPT 助手）：',
  '',
  '一、先牢记当前项目运行环境',
  '1. index.js 必须导出函数：module.exports = async function buildPresentation({ pptx, pptxgenjs, getResourceUrl, getResourcePath, log, projectId, projectDir, path }) { ... }。',
  '2. 可用上下文：',
  '   - context.pptx：当前演示文稿实例，常用枚举也挂在这个实例上，例如 pptx.ShapeType.roundRect、pptx.ChartType.bar、pptx.AlignH.center。',
  '   - context.pptxgenjs：PptxGenJS 构造函数本身，可用于判断实例类型，例如 pptx instanceof pptxgenjs。',
  '   - context.getResourceUrl(fileName)：把项目中的图片/媒体文件转成浏览器可访问地址。',
  '   - context.getResourcePath(fileName)：把项目中的文件转成本地路径（仅后端运行可用）。',
  '   - context.log(...args)：输出运行日志，方便排错。',
  '   - context.projectId / context.projectDir / context.path：当前项目信息。',
  '3. 框架会负责预览、导出和写文件，不要在 index.js 里自己调用 writeFile / write / saveAs。',
  '4. 不要 import / require 外部模块；只能使用框架提供的上下文和标准 JavaScript 语法。',
  '5. 完成内容后要保证脚本能直接运行，优先输出完整可交付的 PPT，而不是只有一页占位页。',
  '',
  '二、推荐起手模板',
  "module.exports = async function buildPresentation({ pptx, getResourceUrl, log }) {",
  "  pptx.layout = 'LAYOUT_WIDE';",
  "  pptx.author = 'last-version-ppt';",
  "  pptx.subject = '自动生成演示文稿';",
  "  pptx.title = '项目标题';",
  "  pptx.company = 'last-version-ppt';",
  "  pptx.lang = 'zh-CN';",
  '',
  '  const slide = pptx.addSlide();',
  "  slide.background = { color: 'F8FAFC' };",
  "  slide.addText('主标题', { x: 0.8, y: 0.7, w: 11.2, h: 1.0, fontSize: 44, bold: true, color: '0F172A' });",
  "  slide.addText('副标题或说明', { x: 0.8, y: 1.9, w: 11.2, h: 0.8, fontSize: 28, color: '475569' });",
  "  log('封面已生成');",
  '};',
  '',
  '三、Presentation 级 API（演示文稿级）',
  "1. 页面比例：pptx.layout = 'LAYOUT_WIDE' | 'LAYOUT_16x9' | 'LAYOUT_4x3'。",
  '2. 自定义比例：pptx.defineLayout({ name: "CUSTOM", width: 13.333, height: 7.5 }); 然后 pptx.layout = "CUSTOM"。',
  '3. 元信息：pptx.author / company / subject / title / lang / theme / rtlMode / layout。',
  '4. 幻灯片：pptx.addSlide() 新增页面；pptx._slides.length 可用于了解当前页数（尽量只读不改内部结构）。',
  '5. 母版与主题：可使用 pptx.defineTheme(...)、pptx.theme = {...}、pptx.defineSlideMaster(...) 统一标题、页脚、背景。',
  '6. 导出相关 API 如 pptx.writeFile()/write() 由框架托管，本项目中不要主动调用。',
  '',
  '四、Slide 级 API（每一页常用能力）',
  '1. 新增页面：const slide = pptx.addSlide();',
  "2. 背景色：slide.background = { color: 'F8FAFC' };",
  '3. 备注：slide.addNotes("讲解备注");',
  '4. 页面编号、页眉页脚、版式可以通过母版或统一函数封装。',
  '5. 常见排版思路：封面 / 目录 / 问题 / 方案 / 亮点 / 数据 / 计划 / 收尾，保证信息完整。',
  '',
  '五、文本 API（最常用）',
  '1. 纯文本：slide.addText("标题", { x, y, w, h, fontSize, bold, color, align, valign });',
  '2. 富文本：slide.addText([{ text: "营收", options: { bold: true } }, { text: " +32%" }], { x, y, w, h });',
  '3. 常用选项：',
  '   - 位置尺寸：x, y, w, h',
  '   - 字体：fontFace, fontSize, bold, italic, color, margin',
  '   - 对齐：align, valign；富文本分段换行时可用 breakLine',
  '   - 背景与边框：fill: { color }, line: { color, pt }',
  '   - 项目符号：bullet: { indent }',
  '   - 段落：paraSpaceAfterPt, paraSpaceBeforePt, breakLine',
  '   - 参考常见 16:9 商务模板：封面大标题常见 44~60、副标题 28~32、页标题 32~40、正文 20~24、备注 16~18。',
  '   - 本项目默认建议：封面主标题 44、页标题 36、副标题 28、正文 24；三栏卡片或表格较密时正文可降到 20。',
  '4. 标题示例：',
  "   slide.addText('年度经营复盘', { x: 0.7, y: 0.5, w: 6.5, h: 0.8, fontSize: 36, bold: true, color: '0F172A' });",
  '5. 简单换行（最稳妥）：',
  "   slide.addText('• 收入同比提升 32%\\n• 新客转化率提升 11%\\n• 重点区域已完成覆盖', { x: 0.9, y: 1.7, w: 5.4, h: 2.5, fontSize: 24, color: '334155' });",
  '6. 富文本分段换行（只有在需要单独控制每段样式时再用）：',
  '   slide.addText([',
  "     { text: '• 收入同比提升 32%', options: { color: '0F766E', breakLine: true } },",
  "     { text: '• 新客转化率提升 11%', options: { color: '1D4ED8', breakLine: true } },",
  "     { text: '• 重点区域已完成覆盖', options: { color: '334155' } }",
  "   ], { x: 6.7, y: 1.7, w: 5.1, h: 2.5, fontSize: 24 });",
  '',
  '六、图片与媒体 API',
  '1. 本地资源优先使用 getResourceUrl("文件名.png")；如果只在后端导出时需要绝对路径，可用 getResourcePath("文件名.png")。',
  '2. 基础写法：slide.addImage({ path: getResourceUrl("cover.png"), x, y, w, h });',
  '3. 常用选项：x, y, w, h, path, data, transparency, rounding。',
  '4. 按比例裁切：slide.addImage({ path, x, y, w, h, sizing: { type: "cover", x, y, w, h } });',
  '5. 完整放入：slide.addImage({ path, x, y, w, h, sizing: { type: "contain", x, y, w, h } });',
  '6. 实战建议：图片不要拉伸变形；人物图适合 cover，海报/截图适合 contain。',
  '',
  '七、形状与线条 API',
  '1. 矩形：slide.addShape(pptx.ShapeType.rect, { x, y, w, h, fill: { color }, line: { color } });',
  '2. 圆角矩形：slide.addShape(pptx.ShapeType.roundRect, { ... });',
  '3. 线条：slide.addText("流程", ...); slide.addShape(pptx.ShapeType.line, { x, y, w, h, line: { color, pt, beginArrowType, endArrowType } });',
  '4. 常见形状：rect、roundRect、ellipse、line、chevron、rightArrow、hexagon。',
  '5. 卡片示例：',
  "   slide.addShape(pptx.ShapeType.roundRect, { x: 0.8, y: 1.6, w: 3.7, h: 1.8, rectRadius: 0.08, fill: { color: 'FFFFFF' }, line: { color: 'E2E8F0', pt: 1 } });",
  '',
  '八、表格 API',
  '1. 基础写法：slide.addTable(rows, { x, y, w, h });',
  '2. rows 是二维数组，例如：',
  "   const rows = [['项目', '数值', '说明'], ['营收', '520 万', '同比增长 32%'], ['毛利率', '48%', '持续改善']];",
  '3. 常用选项：border, fill, color, fontSize, margin, rowH, colW, align, valign。',
  '4. 表头建议加深底色并加粗，数据列右对齐，说明列左对齐。',
  '',
  '九、图表 API',
  '1. 基础写法：slide.addChart(chartType, series, { x, y, w, h, catAxisLabelFontSize, valAxisLabelFontSize, showLegend });',
  '2. 柱状图：pptx.ChartType.bar。',
  '3. 折线图：pptx.ChartType.line。',
  '4. 饼图：pptx.ChartType.pie / pptx.ChartType.doughnut。',
  '5. series 示例：',
  '   const series = [',
  "     { name: '营收', labels: ['一月', '二月', '三月'], values: [120, 180, 240] },",
  "     { name: '利润', labels: ['一月', '二月', '三月'], values: [30, 56, 88] }",
  '   ];',
  '6. 图表建议：页内不要堆太多图；每页一个核心结论，搭配 1 个图和 2~4 条解释。',
  '',
  '十、常见页面模板示例',
  '1. 封面：大标题 + 副标题 + 背景图/品牌色。',
  '2. 目录：3~6 个章节，编号清晰。',
  '3. 三栏亮点页：三个卡片，每个卡片含标题、短句和图标/数字。',
  '4. 数据页：左图右文，图表解释必须写结论。',
  '5. 计划页：时间线 + 节点说明。',
  '6. 结尾页：一句总结 + 下一步动作 + 联系方式/致谢。',
  '',
  '十一、适合本项目的完整示例',
  "module.exports = async function buildPresentation({ pptx, getResourceUrl, log }) {",
  "  pptx.layout = 'LAYOUT_WIDE';",
  "  pptx.title = '新品发布方案';",
  "  pptx.subject = '三页产品发布演示';",
  '',
  '  const cover = pptx.addSlide();',
  "  cover.background = { color: '0F172A' };",
  "  cover.addText('新品发布方案', { x: 0.7, y: 0.9, w: 6.8, h: 1.0, fontSize: 44, bold: true, color: 'FFFFFF' });",
  "  cover.addText('更快上手、更好转化、更强品牌感知', { x: 0.7, y: 2.0, w: 7.8, h: 0.7, fontSize: 28, color: 'CBD5E1' });",
  "  cover.addImage({ path: getResourceUrl('hero.png'), x: 8.2, y: 0.8, w: 4.2, h: 5.8 });",
  '',
  '  const highlights = pptx.addSlide();',
  "  highlights.background = { color: 'F8FAFC' };",
  "  highlights.addText('三大亮点', { x: 0.7, y: 0.5, w: 4, h: 0.8, fontSize: 36, bold: true, color: '0F172A' });",
  '  [',
  "    { title: '更省时间', desc: '关键流程缩短 40%' },",
  "    { title: '更易成交', desc: '转化率提升更明显' },",
  "    { title: '更有辨识度', desc: '统一品牌视觉表达' }",
  '  ].forEach((item, index) => {',
  '    const x = 0.8 + index * 4.1;',
  "    highlights.addShape(pptx.ShapeType.roundRect, { x, y: 1.6, w: 3.5, h: 2.2, rectRadius: 0.08, fill: { color: 'FFFFFF' }, line: { color: 'E2E8F0', pt: 1 } });",
    "    highlights.addText(item.title, { x: x + 0.25, y: 1.9, w: 2.8, h: 0.5, fontSize: 24, bold: true, color: '0F172A' });",
    "    highlights.addText(item.desc, { x: x + 0.25, y: 2.45, w: 2.9, h: 0.9, fontSize: 20, color: '475569' });",
  '  });',
  '',
  '  const plan = pptx.addSlide();',
  "  plan.background = { color: 'FFFFFF' };",
  "  plan.addText('上线计划', { x: 0.7, y: 0.5, w: 4, h: 0.8, fontSize: 36, bold: true, color: '0F172A' });",
  "  plan.addTable([['阶段', '时间', '重点'], ['预热', '第 1 周', '内容种草与预约'], ['发布', '第 2 周', '直播发布与渠道扩散'], ['转化', '第 3-4 周', '重点客户跟进']], { x: 0.8, y: 1.4, w: 6.8, h: 2.8, fontSize: 20, border: { type: 'solid', pt: 1, color: 'CBD5E1' }, fill: 'FFFFFF', color: '334155' });",
  "  plan.addChart(pptx.ChartType.bar, [{ name: '投放重点', labels: ['预热', '发布', '转化'], values: [30, 50, 20] }], { x: 8.0, y: 1.5, w: 4.2, h: 3.2, catAxisLabelFontSize: 18, valAxisLabelFontSize: 16, showLegend: false, chartColors: ['2563EB'] });",
  '',
  "  log('已生成 3 页新品发布方案');",
  '};',
  '',
  '十二、生成时的质量要求',
  '1. 每一页都要有明确标题，重要信息不要只靠一段长文字。',
  '2. 页数、结构、内容必须符合用户要求；如果用户要完整方案，不要只给简单骨架。',
  '3. 优先使用中文文案，避免英文占位词。',
  '4. 图片、表格、图表需要与页面结论一致，不能只堆元素。',
  '5. 输出前自检：是否有封面、核心内容页、收尾页；是否排版整齐；是否容易读懂。',
].join('\n');
